alpa/device_mesh.py
alpa/global_env.py
alpa/measure_record.py
alpa/mesh_executable.py
alpa/mesh_profiling.py
alpa/monkey_patch.py
alpa/pipeline_parallel/base_runtime.py
alpa/pipeline_parallel/computation.py
alpa/pipeline_parallel/decentralized_distributed_runtime.py
alpa/pipeline_parallel/pipeshard_parallel.py
alpa/pipeline_parallel/stage_profiling.py
alpa/shard_parallel/auto_sharding.py
alpa/shard_parallel/shard_callable.py
alpa/testing.py
alpa/util.py
benchmark/alpa/benchmark_2d_one_case_gpt_bert.py
benchmark/alpa/benchmark_2d_one_case_moe.py
benchmark/alpa/benchmark_2d_one_case_wresnet.py
tests/test_auto_sharding_basic.py
tests/test_auto_sharding_bert.py
tests/test_auto_sharding_conv.py
tests/test_auto_sharding_gradient_accumulation.py
tests/test_auto_sharding_mlp.py
tests/test_auto_sharding_moe.py
tests/test_device_mesh.py
tests/test_hlo_cost_model.py
tests/test_pipeline_stage_construct_util.py

Currently, we run auto-sharding, spmd partitioner, and HLO optimization pipeline on the driver; run Cuda codegen on workers.
However, there is a CUDNN/CUBLAS auto-tuning pass in the HLO optimization pipeline, which requires GPU memory. Because all GPU memory is occupied by the workers, this pass cannot be executed on the driver. Currently, this pass is disabled to resolve the memory conflicts. However, this pass is critical for cudnn's performance. In this PR, we move the HLO optimization pipeline to workers and resolve the memory conflict, so we can enable this pass again.
This PR reorganizes passes and refactored the auto sharding pass APIs in `alpa/shard_parallel/auto_sharding.py`
The status of an HLO module is described below. …

 Reorganize passes and build options

---

docs/install/from_source.rst

The installation guide `pip3 install flax` will install flax 0.4.1 in default, which is not compatible with current jax-alpa (jax==0.2.26). The resulting error may occur when import alpa, which is quite obscure.

[Documentation] install flax==0.4.0

---

alpa/pipeline_parallel/stage_profiling.py
alpa/shard_parallel/auto_sharding.py

`bypass_device_assignment_check` is still required for HloCostModelProfiler. This pr brings it back.

[Fix] Fix device assignment check

---

alpa/device_mesh.py
alpa/pipeline_parallel/computation.py

This is an extreme case discovered in an ablation study that cluster layers by equal operators. To fix it, the `offload_remat` pass is rewritten into two parts:
the first decides which `remat_call` can be offloaded, and eliminates the computation's output;
the second finds all computations using these outputs, inserting all offloaded eqns into each user. If some eqns are inserted but is redundant, it can be eliminated by Inline+DCE in XLA.

[FIX] Fix the case that remat_call output used in other mesh

---

alpa/global_env.py
alpa/mesh_profiling.py
alpa/monkey_patch.py
benchmark/alpa/README.md
benchmark/alpa/gen_prof_database.py
tests/test_auto_sharding_basic.py
tests/test_hlo_cost_model.py

Improve the nccl communicator initialization, which greatly reduces the number of failures and retries during generating the profiling database.
The key is that we should not create the NCCL communicator in an HLO with while loop.

[PROFILING] Fix mesh profiling

---

alpa/collective/collective_group/gloo_collective_group.py
alpa/device_mesh.py
alpa/global_env.py
alpa/monkey_patch.py
docs/install/from_source.rst
tests/test_auto_sharding_basic.py
tests/test_dist_save_load.py

I added two methods for class DistributedArray: 
- save(path)  will save only one replica of the data that the DistributedArray's remote_buffers point to. This function can be called in the driver and it will dispatch the saving process to the MeshHostWorker, which uses TensorStore package to save the DeviceArray into EFS.
- load(path) will dispatch the loading process to the MeshHostWorker, which uses TensorStore package to load the data stored in EFS into the buffers.
The saved and loaded DistributedArray can have different ShardingSpec, so I think this can be the starting point for the model's distributed save/load.
You can also check the test_dist_save_load.py unit test.

[RUNTIME] Save/Load DistributedArray on each Host node distributedly

---

alpa/pipeline_parallel/stage_construction.py

The current logic of `uniform_stage` in `cluster_layers_and_slice_mesh` is wrong. For example it will generate 2 2x2 meshes when slicing 2 pipeline stages on a 2x4 device mesh. Also `uniform_slice_mesh` is unused now.

[BUG] Fix uniform stage

---

alpa/device_mesh.py
alpa/global_env.py
alpa/mesh_executable.py
alpa/pipeline_parallel/base_runtime.py
alpa/pipeline_parallel/centralized_distributerd_runtime.py
alpa/pipeline_parallel/decentralized_distributed_runtime.py
alpa/pipeline_parallel/local_pipeline_parallel.py
alpa/pipeline_parallel/pipeshard_parallel.py
tests/README.md
tests/test_cross_mesh_resharding.py

No functional change.
- do not use `self.xxx` to pass arguments or return values when unnecessary.
- remove unnecessary `list(x)` around np arrays
- fix wrong or outdated comments

[Refactor] Clean up the compliation in distributed pipeline runtime

---

alpa/device_mesh.py
alpa/mesh_executable.py

Probably missing unit test for shape-only input when benchmark mode is on.

Fix support for shape-only input

---

alpa/__init__.py
alpa/device_mesh.py
alpa/pipeline_parallel/decentralized_distributed_runtime.py
alpa/pipeline_parallel/pipeshard_parallel.py
alpa/serialization.py
tests/test_dist_save_load.py

I added two top-level APIs for Alpa: 
- save_checkpoint(ckpt_dir, target, step): the `target` is usually the trainState. This function (1) replaces the leaves of trainState (DistributedArray or ReplicatedDistributedArray) with the path to which the array is saved and saves this metadata for restore. (2) saves one replica for all the DistributedArrays/ReplicatedDistributedArrays in `target`.
- restore_checkpoint(executable, ckpt_dir, target, step): This function requires the DecentralizedRuntime which contains all the shardingSpec and mesh allocation info to load and reshard the DistributedArrays/ReplicatedDistributedArrays. 
Current version contains a defect that the trainState must be the first argument in the parallelized function (i.e. train_step). One possible fix requires the user to …

[RUNTIME] Distributed Save and Load for Model

---

alpa/pipeline_parallel/xla_custom_call_marker/build.sh

This PR allows user to specify their CUDA install location for xla_custom_call_marker build.

Allow using CUDA_HOME setting in xla_custom_call_marker build

---

alpa/pipeline_parallel/pipeshard_executable.py
alpa/serialization.py
tests/test_pipeline_mlp.py

A KeyError is raised when an input arg is never used. This is because load cannot find its corresponding sharding spec. This PR returns None and log a warning in case of that.

[FIX] skip load if var is not used

---

alpa/device_mesh.py
alpa/serialization.py
tests/test_dist_save_load.py

Current restore_checkpoint only supports loading from tensorstore. In order to load the 175B OPT model, we should save the model's ndarray version into tensorstore first. I modified `serialization.py` so that now `save_checkpoint` will automatically save ndarray into tensorstore.

[RUNTIME] Save normal jax model into tensorstore for distributed loading

---

alpa/serialization.py
tests/test_dist_save_load.py

The `target` argument in restore_checkpoint is redundant. Use `load_info` instead.

[RUNTIME] Simplify restore_checkpoint() API

---

alpa/monkey_patch.py

Similar to `fast_uniform` and `fast_normal`, `fast_bernoulli` is a bernoulli RNG function that supports `key=None`.

Add fast_bernoulli

---

alpa/device_mesh.py

With `shard_and_apply_func_on_buffer`, we can support remote weight initialization directly on the workers.
Example `apply_func` that's passed into `shard_and_apply_func_on_buffer` looks like:
```python
def init_buffer(init_func,
init_func_kwargs,
local_rng_seed,
worker,
uuid: int,
device_id: int,
shape: Sequence[int],
dtype=np.dtype(np.float32)):
torch_local_rng = torch.Generator()
torch_local_rng.manual_seed(local_rng_seed)
init_func_kwargs["rng"] = torch_local_rng
init_func_kwargs["shape"] = shape
init_func_kwargs["dtype"] = numpy_to_torch_dtype_dict[dtype]
worker.buffers[uuid] = (worker.backend.buffer_from_pyval(
init_func(**init_func_kwargs), worker.local_devices[device_id]))
```
and is called with
```python
device_mesh.workers[host_id].shard_and_apply_func_on_buffer.remote( …
```

Add shard_and_apply_func_on_buffer for remote weight initialization on worker

---

alpa/__init__.py
alpa/model/bert_model.py
alpa/model/moe.py
alpa/pipeline_parallel/layer_construction.py
alpa/pipeline_parallel/primitive_def.py
alpa/testing.py
benchmark/alpa/benchmark_3d_one_case_gpt_bert.py
docs/gallery/tutorials/pipeshard_parallelism.py
tests/test_pipeline_bert.py
tests/test_pipeline_inference_only.py
tests/test_pipeline_marker.py
tests/test_pipeline_mlp.py
tests/test_pipeline_tied_embedding.py

The current manual pipeline API is tedious.
Require a "start" and an "end" marker for each stage.
```python
class MLP(nn.Module):
@nn.compact
def __call__(self, x):
x = nn.Dense(features=self.hidden_dim * 4)(x)
alpa.mark_pipeline(name='0', mark_type='end')
alpa.mark_pipeline(name='1', mark_type='start')
x = nn.Dense(features=self.hidden_dim * 4)(x)
return x
@alpa.parallelize
def train_step(state, batch):
@alpa.manual_layer_construction
def loss_func(params):
alpa.mark_pipeline(name='0', mark_type='start')
out = state.apply_fn(params, batch["x"])
loss = jnp.mean((out - batch["y"])**2)
alpa.mark_pipeline(name='1', mark_type='end')
return loss
```
Only require a `mark_pipeline_boundary` at the stage boundary. No need to add any markers in `loss_func`.
```python
class MLP(nn.Module): …
```

[API] Simplify manual pipeline API

---

alpa/__init__.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/computation.py
alpa/pipeline_parallel/stage_profiling.py
alpa/shard_parallel/auto_sharding.py
alpa/shard_parallel/compile_executable.py
alpa/util.py

`HloModule` is more flexible than `XlaComputation`. This PR modifies most of alpa compiler's interfaces such as `run_auto_sharding_pass`, `run_spmd_partitioner_pass` and `slice_auto_sharded_stages` to take HloModule as input and return HloModule.

Use HloModule instead of XlaComputation in alpa compiler's interfaces

---

alpa/device_mesh.py
alpa/pipeline_parallel/pipeshard_executable.py
alpa/pipeline_parallel/runtime_emitter.py
alpa/serialization.py
playground/alpa_micro_benchmark/benchmark_dist_save_load.py
tests/test_dist_save_load.py

This PR improves alpa's model checkpoint functions according to #466.
- The on-disk file names are readable and deterministic.
I dfs the pytree and construct the filename according to the path from the root to leaf. 
For example: 
```
state = {"step": 1, "params": {"x": arr1, "b": arr2}, "list": [elem1, elem2]}
```
The paths for each element will be:
```
1 => state.step
arr1 => state.params.x
arr2 => state.params.b
elem1 => state.list.0
elem2 => state.list.1
```
- The paths stored in metadata are relative paths.
All the benchmark results are in `alpa/playground/alpa_micro_benchmark/benchmark_dist_save_load.py`.
The peak bandwidth of load is measured by running a jax program that reads a 1GB numpy array from disk to local GPU memory. Ditto for save. The results are as followed:
``` …
```

[RUNTIME] Model Checkpoint Improvements

---

alpa/device_mesh.py

```python
host_info = [{'NodeID': '7a4a9521b1e383121a6af17718cba9154729f1eb0d344af35cb11959', 'Alive': True, 'NodeManagerAddress': '10.0.1.138', 'NodeManagerHostname': 'ip-10-0-1-138', 'NodeManagerPort': 34745, 'ObjectManagerPort': 46437, 'ObjectStoreSocketName': '/tmp/ray/session_2022-06-09_16-34-44_778463_7642/sockets/plasma_store', 'RayletSocketName': '/tmp/ray/session_2022-06-09_16-34-44_778463_7642/sockets/raylet', 'MetricsExportPort': 44366, 'NodeName': '10.0.1.138', 'alive': True, 'Resources': {'node:10.0.1.138': 1.0, 'object_store_memory': 59759950233.0, 'accelerator_type:T4': 1.0, 'GPU': 4.0, 'CPU': 48.0, 'memory': 129439883879.0}}]
```
Then, `sum(host_info)` reports the error `TypeError: unsupported operand type(s) for +: 'int' and 'dict'`
I guess, this is a typo.

fix `num_host`

---

alpa/torch/nn/__init__.py
tests/torch/test_torch_reshape.py

`meta_like` is the better approach which is recently added to torchdistx (https://github.com/pytorch/torchdistx/pull/24).
We need this to enable PyTorch CI test.

Use torchdistx.fake.meta_like for fake->meta conversion

---

alpa/device_mesh.py

According to this [issue](https://github.com/ray-project/ray/issues/6240), it is appropriate to initialize Ray actor in the driver process. This pr moves the initialization of `DaemonMoveWorker` from `MeshHostWorker` into `DistributedPhysicalDeviceArray`.

[RUNTIME] initialize move_worker in driver process

---

alpa/mesh_executable.py
alpa/model/gpt_model.py
format.sh

Sometimes we need to request a size 1 array from `next_remote_buffer_uuid`, and the previous implementation will directly return a number instead of a numpy array. Also fix an error in `format.sh` that requires `pylint-quote` that is no longer needed.

[FIX] Fix a bug in next_remote_buffer_uuid

---

docs/install.rst

I'm following build from source guide in the docs:https://alpa-projects.github.io/install.html#install-from-source on zsh and it will complain `zsh: no matches found: .[dev]` 
Adding this quote helps to make installation successful.

[Docs] Quote ".[dev]" in installation guide 

---

alpa/collective/collective.py
alpa/collective/collective_group/base_collective_group.py
alpa/collective/collective_group/nccl_collective_group.py
alpa/collective/collective_group/xla_nccl_collective_group.py
alpa/collective/collective_group/xla_nccl_util.py
alpa/collective/mesh_run_nccl_collective.py
alpa/collective/types.py
alpa/device_mesh.py
alpa/global_env.py
alpa/util.py
docs/gallery/tutorials/alpa_vs_pmap.py
examples/opt_serving/benchmark/benchmark_text_gen.py
examples/opt_serving/generator.py
examples/opt_serving/textgen_demo.py
tests/runtime/test_xla_nccl.py
tests/test_pybind_nccl.py

This PR for [#issue432](https://github.com/alpa-projects/alpa/issues/432). It replaces the independent cupy nccl api with nccl api used in tensorflow-alpa. tensorflow-alpa repo is also changed correspondingly [#PR116](https://github.com/alpa-projects/tensorflow-alpa/pull/116). They should be merged togather so as to run successfully. 
To use the new api, we need to set `global_config.nccl_mode = "from_xla_extension"` To use cupy nccl apis, set it to `"from_cupy"`. In this PR, I have already set it to "from_xla_extension" by default. If the new api keeps running successfully after being tested by all of you. We could then finally deprecate cupy nccl api.  
I tested Alpa with the new api on 
1. gpt-8gpu, gpt-16gpu, gpt-32gpu, gpt-64gpu, moe-8gpu, moe-16gpu, wresnet-8gpu and wresnet-16gpu in …

[Feature]Deprecate cupy nccl api and change to use nccl imported from tensorflow-alpa

---

alpa/global_env.py

The xla nccl backend still has a flaky numerical correctness bug.

[FIX] Revert cross-mesh resharding mode to cupy

---

alpa/device_mesh.py
alpa/global_env.py
alpa/mesh_executable.py
examples/opt_serving/benchmark/benchmark_step_func.py
examples/opt_serving/benchmark/benchmark_text_gen.py
examples/opt_serving/model/opt_model.py
tests/runtime/test_memory_leak.py

Fix several bugs after #556 
I can confirm the speed of opt-2.7b on p3.16 goes from 44 token/s to 50 token/s after the refactor

[Fix] Fix OPT example after UUID refactor

---

alpa/device_mesh.py
alpa/util.py
examples/opt_serving/model/opt_model.py
examples/opt_serving/model/wrapper.py
examples/opt_serving/textgen_demo.py

This PR adds reorder cache function to support the beam sample. It modifies some apis in `opt_serving/model/wrapper.py` to add config for beam number.

[FEATURE] Support beam sample

---

alpa/create_state_parallel.py
alpa/data_loader.py
alpa/device_mesh.py
alpa/global_env.py
alpa/mesh_executable.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/layer_construction.py
alpa/pipeline_parallel/pipeshard_executable.py
alpa/pipeline_parallel/runtime_emitter.py
alpa/torch/optim/adam.py
examples/imagenet/train.py
tests/runtime/test_create_state.py
tests/runtime/test_data_loader.py

- Use the more generate `PlacementSpecs` instead of `ShardingSpec` in data loaders.
- Add `get_output_placement_specs` in mesh executables.

[DataLoader] Use PlacementSpecs in data loader

---

alpa/test_install.py
docs/developer/developer_guide.rst
docs/install.rst
tests/runtime/test_install.py

Now we can use the commands below to test the installation, so people who install alpa by wheel can also run the tests
```
python3 -m alpa.test_install
```

[Docs] Move test install to alpa package

---

alpa/__init__.py
alpa/create_state_parallel.py
alpa/mesh_executable.py
alpa/monkey_patch.py
alpa/parallel_method.py
alpa/parallel_plan.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/computation.py
alpa/pipeline_parallel/pipeshard_executable.py
alpa/pipeline_parallel/runtime_emitter.py
alpa/pipeline_parallel/schedules.py
alpa/pipeline_parallel/stage_construction.py
alpa/shard_parallel/auto_sharding.py
playground/jax_basic/test_sharding_spec.py
tests/runtime/test_parallel_plan.py

Now we can serialize a parallel plan and reuse it. Currently, it only supports pickle, which is not good for backward compatibility. We can design a better format later.
```python
plan = executable1.get_parallel_plan()
with open("tmp_plan.pkl", "wb") as fout:
pickle.dump(plan, fout)
with open("tmp_plan.pkl", "rb") as fin:
plan = pickle.load(fin)
p_train_step = parallelize(train_step, method=plan_to_method(plan))
executable2 = p_train_step.get_executable(state, batch)
```

[FEATURE] Serialize Parallel Plan

---

examples/opt_serving/model/wrapper.py
examples/opt_serving/textgen_demo.py

Add `alpa.global_config.xla_client_mem_fraction = 0.88` to give more GPU memory for pytorch

[OPT] Fix pytorch OOM issue

---

docs/install.rst

We are already in the alpa folder at this point, we hence need to move one step shorter. The instructions to runs installation verification tests are also not working as is, and the instructions have been amended as such.

[Doc] Update path to jaxlib build

---

alpa/create_state_parallel.py
alpa/parallel_method.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/computation.py
alpa/pipeline_parallel/pipeshard_executable.py
alpa/pipeline_parallel/runtime_emitter.py
tests/pipeline_parallel/test_set_input_shard.py

A part of #550: Manual inter-operator parallelism and sharding-propagation based intra-operator parallelism
Improve `PipeshardParallel` to optionally accept `input_sharding`. When given, the input of each HLO module will be sharded accordingly.
See unit test for details.
cc @merrymercy @zhuohan123

[Feature] Support input sharding specs assignment

---

examples/opt_serving/service/index.html

We ran into some trouble hosting the OPT demo behind a reverse proxy like NGINX that adds a prefix to the OPT serving URLs. This PR changes the completions request to use a relative URL so the OPT service can work under and reverse proxy.

Use relative path to access completions URL

---

alpa/__init__.py
alpa/create_state_parallel.py
alpa/device_mesh.py
alpa/follow_parallel.py
alpa/mesh_executable.py
alpa/parallel_method.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/computation.py
alpa/pipeline_parallel/layer_construction.py
alpa/pipeline_parallel/runtime_emitter.py
alpa/pipeline_parallel/stage_profiling.py
alpa/shard_parallel/compile_executable.py
alpa/util.py
tests/runtime/test_follow_parallel.py

We can use `method=FollowParallel()` to let a function follow the parallelization strategy of another function. For example, let eval_step follow the train_step.
```python
train_step = parallelize(train_step, method=method)
eval_step = parallelize(eval_step,
method=alpa.FollowParallel(
train_step,
num_micro_batches=num_micro_batches))
```
This works for both ShardParallel and PipeshardParallel.

[FEATURE] Add FollowParallel

---

alpa/device_mesh.py
alpa/pipeline_parallel/stage_construction.py
alpa/pipeline_parallel/stage_profiling.py
alpa/util.py
setup.py

This PR is to make use of placement group to create meshworkers. This new approach gives alpa more freedom to allocate the resources. 
Previous issue: #618 
----
benefits: 
---------
why: currently alpa prefix the actor to the ip which might not be that flexible for the ray tune; if we have ip-address as the resources for ray tune, the tune process can not go to another machine.
Example: 2 node with 4 gpu each
Expected tune behaviors: "GPU": 1 as the resource for each tune process, then 8 process tuning together with 4 on each node.
Currently behaviors: "GPU": 1, "ip_A": 1e-3 as the resources, the process is fixed on ip_A
Action: use the workergroup defined here (https://github.com/ray-project/ray/blob/master/python/ray/train/_internal/worker_group.py#L72-L84), and there are some method …

[Internal feature: Ray Placement Grp] adding the placement group 

---

alpa/api.py
alpa/device_mesh.py
tests/run_all.py
tests/runtime/test_device_mesh.py

> Hello! Sorry maybe a silly question, but is there a configuration for alpa to use only a subset of the # of gpus? (Ie. only run 2 cores when 8 cores are available) Do I have to create a device mesh for it? 
People prefer to set the configuration for the alpa instead of using the whole cluster. This PR is try to enrich the resources allocation with a easy-to-use api.
@zhisbug @merrymercy

[Alpa Runtime] update the alpa api for resources awareness

---

examples/opt_finetune/README.md
examples/opt_serving/README.rst
examples/opt_serving/benchmark/benchmark_text_gen.py
examples/opt_serving/generator.py
examples/opt_serving/model/opt_model.py
examples/opt_serving/model/wrapper.py
examples/opt_serving/textgen_demo.py

- **API CHANGE**. Update the argument of `get_model` and improve the docstrings
- `device` is renamed to `torch_device`.
- `encoder_seq_lengths` is renamed to `encoder_chunk_sizes`
-  Some order changes
- Change the default torch device to CPU to avoid memory conflicts
- Use multiple executables by default

[OPT] Change the default torch device to CPU & Use multiple executables by default

---

examples/opt_serving/model/opt_model.py
examples/opt_serving/model/opt_model_1d.py
examples/opt_serving/model/test_1d.py

This PR adds an 1-D OPT model implementation. See `test_1d.py` for model inputs and output.
Some highlights:
1. The model uses the fused kernel from `ft_mha`. The corresponding repo should be included in alpa-project, but it's not publicly available now.
2. With the fused MHA kernel, we still have to update the attention cache. I haven't implemented it because I haven't figured out how.
3. Currently I verified that the output of a batch of prompts from both 1D and 2D model are identical, so does the cache shape. However, based on 2, I commented out the cache value checking.

[OPT] 1-D OPT model with fused MHA

---

examples/opt_serving/client.py
examples/opt_serving/generator.py
examples/opt_serving/interactive_hosted.py
examples/opt_serving/test_logprobs.py

Hi, 
I implemented a limited version of batching for the logprobs endpoint. Specifically, the user can now send up to `MAX_BS` prompts together, each with the same number of tokens, and they'll be processed and cached together as one WorkItem. Then the user can update each of those prompts by one token and re-query with the same batch in the same order. I modified `test_logprobs.py` to show an example. 
This should be all that I need for my use case, but it currently doesn't support mixing prompts from different batches, or using prompts of different lengths in the same batch. The latter is checked via an assert; without the assert, it will run without crashing, but the result is incorrect even after I ensure the `input_ids` and `attention_mask` are correct, so I assume there's something …

limited batching support for logprobs endpoint

---

docs/gallery/tutorials/pipeshard_parallelism.py

this pr is to add the explanation of using the new api (https://github.com/alpa-projects/alpa/pull/657). 
Not sure this is the best place to add the description, but it will show in the [online tutorials](https://alpa.ai/tutorials/pipeshard_parallelism.html#connect-to-a-ray-cluster). 
@zhisbug

[doc] adding the doc to describe the new api

---

docs/gallery/tutorials/quickstart.py

Docstring says 
```
The body of this function is the same as the ``train_step`` above. The only difference is to decorate it with ``alpa.paralellize``.
```
But it's not quite the case in docs. We should have the right drop-in replacement impression for user.

[Docs] Update the the doc to use same snippet between jax & alpa train_step

---

examples/llm_serving/model/wrapper.py

Add fields suppress_tokens, begin_suppress_tokens, and forced_decoder_ids as they are needed by transformer from 4.23.

[LLM_Serving] Update InferenceFuncConfig to support transformer 4.23

---

.gitignore
alpa/pipeline_parallel/pipeshard_executable.py
alpa/timer.py
benchmark/alpa/README.md
benchmark/alpa/benchmark.py
benchmark/alpa/benchmark_one_case.py
benchmark/alpa/benchmark_one_case_gpt_bert_inference.py
benchmark/alpa/benchmark_parallel_utils.py

Usage: in `alpa/benchmark/alpa`, run
```
python benchmark.py --suite gpt_inference.profile --profile_stage_execution_time
```
the chrome tracing files will be saved under `./chrome_trace/`.

[PROFILE] Dump pipeline stage execution timeline into chrome tracing file in inference benchmark

---

alpa/device_mesh.py
benchmark/alpa/benchmark.py
benchmark/alpa/benchmark_one_case_gpt_bert_inference.py
benchmark/alpa/benchmark_parallel_utils.py
benchmark/alpa/run_exp.py
benchmark/alpa/suite_inference_gpt.py

- Add per-stage latency to benchmark output.
- To benchmark `bert-1.3b`, run `MODEL_NAME="bert-1.3b" python run_exp.py gpt_inference` under `benchmark/alpa/`, the output will be in `bert-1.3b.tsv` under the same folder.

[BENCHMARK] Align the benchmark output format with the requirements of Alpa Serve

---

alpa/__init__.py
alpa/collective/collective_group/nccl_util.py
alpa/create_state_parallel.py
alpa/device_mesh.py
alpa/follow_parallel.py
alpa/global_env.py
alpa/mesh_executable.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/computation.py
alpa/pipeline_parallel/primitive_def.py
alpa/pipeline_parallel/stage_profiling.py
alpa/shard_parallel/auto_sharding.py
alpa/shard_parallel/compile_executable.py
alpa/util.py
setup.py
tests/run_all.py
tests/runtime/test_create_state.py
tests/runtime/test_follow_parallel.py
tests/shard_parallel/test_mlp.py
tests/shard_parallel/test_moe.py
tests/tpu/test_create_state_parallel.py
tests/tpu/test_follow_parallel.py
tests/tpu/test_shard_parallel.py

This PR:
- Add `has_cuda` and `backend` in `global_config`
- Add `IS_CUDA` in `setup.py`
- Change the semantic of `run_auto_sharding_pass` and `run_backend_compilation`: the output of the `run_auto_sharding_pass` and input of `run_backend_compilation` is no longer the spmd-partitioned module, but instead the sharding annotated module. This is because TPU cannot compile an spmd-partitioned module with sharding configurations;
- write testcases specifically for TPUs. The pass that rewrites `AllReduce` to `ReduceScatter` and `AllGather` is after SPMD partitioner, so we cannot do it for the tpu backend.

[Feature] Support TPU backend for ShardParallel

---

alpa/device_mesh.py
alpa/pipeline_parallel/stage_profiling.py

Fix https://github.com/alpa-projects/alpa/issues/776#issuecomment-1315111925

[FIX] Use the ip address of the profile worker as XLA server address & fix available memory memory bug in distributed profiling

---

alpa/__init__.py
alpa/create_state_parallel.py
alpa/follow_parallel.py
alpa/mesh_executable.py
alpa/parallel_method.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/computation.py
alpa/pipeline_parallel/pipeshard_executable.py
alpa/shard_parallel/auto_sharding.py
alpa/shard_parallel/compile_executable.py
alpa/shard_parallel/manual_sharding.py
alpa/testing.py
alpa/util.py
alpa/wrapped_hlo.py
benchmark/alpa/resharding/benchmark_cross_mesh_resharding.py
tests/pipeline_parallel/test_cross_mesh_resharding.py
tests/pipeline_parallel/test_manual_sharding.py
tests/shard_parallel/test_manual.py

Background
---
This PR provides an option to manually config the strategy of `ShardParallel`. It adopts the input the same as `pjit`, but replaces its `Mesh` by Alpa's `LogicalMesh`, which does not need physical resources. The api is supposed to have:
```python3
class ManualShardingOption:
in_axis_resources: Optional[PyTree] = pjit._UNSPECIFIED,
out_axis_resources: Optional[PyTree] = pjit._UNSPECIFIED,
mesh_axis_names: Sequence[str] = None,
def get_sharding_spec(avals, axis_resources, logical_mesh, mesh_axis_names, option: ManualShardingOption):
"""Translate the axis resources of each aval into the ShardingSpec of each var."""
```
With the sharding spec of each var, we can then use `hlo_module.set_spmd_parameters_shardings` or `set_spmd_output_sharding` to set the sharding spec of the …

[RFC][FEATURE] support manual parallelization strategy in shard parallel

---

benchmark/cupy/profile_communication.py
docker/README.md
docker/build_jaxlib.Dockerfile
docker/coreweave/README.md
docker/coreweave/cluster.yaml
docker/coreweave/run_alpa_infiniband.Dockerfile
docker/run_alpa.Dockerfile

Add complete guide to deploy Alpa on CoreWeave cloud (k8s with infiniband). See added documentation page for more details.
In addition, this PR makes a few changes to current Alpa codebase:
- Changed `profile_communication.py` to add an `ib` flag
- Changed docker documentation page to use `main` branch instead of `master`
- Changed default wheel from `jaxlib==0.3.15` to `jaxlib==0.3.22`.
- Added keys to `docker/build_jaxlib.Dockerfile`

Add k8s/infiniband build and deployment guide to Alpa

---

alpa/mesh_executable.py
alpa/pipeline_parallel/pipeshard_executable.py

Having input/output placement specs help to debug sharding strategies in our t5 development. Example output for a shard parallel output:
```
(TrainState(step=PlacementSpec(aval=ShapedArray(int32[]), mesh_ids=(0,), sharding_specs=(ShardingSpec((), (Replicated(replicas=2),)),)), apply_fn=<bound method Module.apply of MLPModel(	
num_layers = 4	
hidden_size = 16	
use_bias = True	
add_manual_pipeline_marker = False	
)>, params=FrozenDict({	
params: {	
Dense_0: {	
bias: PlacementSpec(aval=ShapedArray(float32[16]), mesh_ids=(0,), sharding_specs=(ShardingSpec((Chunked(2),), (ShardedAxis(axis=0),)),)),	
kernel: PlacementSpec(aval=ShapedArray(float32[16,16]), mesh_ids=(0,), sharding_specs=(ShardingSpec((NoSharding(), Chunked(2)), (ShardedAxis(axis=0),)),)),	
},	
Dense_1: {	
bias: …
```

Add input/output sharding specs to dump_debug_info()

---

benchmark/cupy/profile_communication.py

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-ib-hca
NCCL by default takes a list of interfaces in case host has different NICs.

[InifiniBand] Add mlx5 interface to alpa NCCL test

---

alpa/collective/collective.py
alpa/collective/worker_nccl_util.py
alpa/collective/worker_nccl_util_cupy.py
alpa/collective/worker_nccl_util_xla.py
alpa/device_mesh.py
tests/pipeline_parallel/test_cross_mesh_resharding.py

The `global_config.nccl_mode` is intended to control the nccl used by cross-mesh communication. However, currently it does so by selecting which class to import, which makes it impossible to make effects when the user changes it after importing alpa. This pr aims to solve it.

[FIX] fix the function of nccl_mode

---

alpa/serialization.py

`alpa.restore_checkpoint` only works when a `PhysicalDeviceMeshGroup` (eg. `VirtualPhysicalMesh`) exists in cases such as `PipeshardParallel`. 
However, `ShardParallel` uses `PhysicalDeviceMesh`, meaning `get_global_virtual_physical_mesh().launched_physical_mesh_group` will return None. 
This PR bypasses the mesh_group in these cases to allow `ShardParallel` checkpoints to be restored to the physical mesh.

[FIX] restore_checkpoint without mesh group

---

alpa/util.py

numpy does not support BF16, so we should use jax numpy datatypes instead

use jax dtype for BF16

---

examples/llm_serving/launch_model_worker.py
examples/llm_serving/service/constants.py
examples/llm_serving/service/scheduler.py

See the issue page https://github.com/alpa-projects/alpa/issues/700. I made some design choices based on my comment there, see if the design choices make sense.

[FEATURE] OPT-175B service authentication and new priority queue

---

alpa/parallel_method.py
alpa/pipeline_parallel/apply_grad.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/runtime_emitter.py

1. Prune pipeline markers to avoid redundant in/out vars;
2. Fix 1f1b overlap friendly schedule when sending a var to multiple meshes

[FIX] misc fix for t5x

---

alpa/pipeline_parallel/apply_grad.py
alpa/pipeline_parallel/stage_construction.py

The previous `UniformStageOption` uses "`flops_if_cut_here` is the closest to `average_flops_per_stage`" to divide a stage, however, this tends to divide a stage slightly smaller than the average. The shift accumulates and thus the last stage may not end at the last layer, but some layers before. This pr fixes the bug by cutting at "`flops_till_now` is the closest to `average_flops_per_stage * stage_idx`"

[FIX] explicit stage num with uniform stage divided by flops

---

setup.py

Alpa doesn't have to depend on a really old version of Ray.
Relax to depend on the latest version.

Update setup.py to depend on latest Ray

---

alpa/collective/collective_group/base_collective_group.py
alpa/collective/collective_group/nccl_collective_group.py
alpa/collective/collective_group/xla_nccl_collective_group.py

Right now the id actor is detached and deleted by "supposedly" the last user of the actor.
However when execution order is not determined, this will crash the entire workload if the killed named actor is accessed again.
This change make the actor fate-share with worker rank 0. so Rendezvous would not need to kill it.
Closes #907

Let NCCL ID store fate share with CollectiveGroup.

---

alpa/device_mesh.py

closes #837 (1st part)
Although the changes do not significantly reduce total execution time for use cases like _llm_serving (e.g., examples/llm_serving -> python3 textgen.py --model alpa/opt-2.7b)_, new dictionary lookups are generally faster by a factor of 5-10 than computing one_replica_ids.

Moved _compute_one_replica_ids from DistributedArray to PhysicalDeviceMesh

---

alpa/collective/collective_group/gloo_util.py
alpa/collective/collective_group/nccl_util.py

removed from mapping because they're deprecated

removed mapping of numpy.int and numpy.float to nccl and gloo types

---

alpa/collective/worker_nccl_util_cupy.py
alpa/collective/worker_nccl_util_xla.py
alpa/device_mesh.py
alpa/global_env.py
alpa/model/model_util.py
alpa/pipeline_parallel/local_pipeline.py
alpa/serialization.py
alpa/util.py

Shifting from jax 0.3 to 0.4, tensor at the jax level uses `ArrayImpl` to replace `DeviceArray`. The `DeviceArray` class now represents the xla level bare buffer.
This pr is the initial fix for that shift. In the future, we should deprecate all use of `DeviceArray` and `ShardedDeviceArray`, and instead use `ArrayImpl` because it will be the only api in jax.

[FIX] Replace DeviceArray by Array

---

alpa/device_mesh.py
alpa/global_env.py
alpa/pipeline_parallel/compile_executable.py
alpa/pipeline_parallel/schedules.py
alpa/shard_parallel/manual_sharding.py
tests/pipeline_parallel/test_manual_sharding.py

1. Pass the `global_config` to `MeshHostWorker`'s constructor. This allows a user to specify nccl related configs and more;
2. Set manual sharding of intermediate tensors. Prior to this, we can only set data parallelism for intermediate stages with global inputs like `attention_mask`.

[FEATURE] pass global config to worker and set manual sharding of intermediates

---

alpa/collective/collective_group/gloo_util.py
alpa/collective/collective_group/nccl_util.py

I got this error while installing alpa from source:
```
In [1]: import alpa
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 import alpa
File ~/src/alpa/alpa/__init__.py:3
1 """Alpa is a system for training large-scale neural networks."""
2 # Import all public packages
----> 3 from . import api
4 from . import collective
5 from . import create_state_parallel
File ~/src/alpa/alpa/api.py:13
10 from jax.experimental.maps import FrozenDict
11 from jax.tree_util import tree_flatten, tree_unflatten, PyTreeDef
---> 13 from alpa.device_mesh import init_global_cluster, shutdown_global_cluster
14 from alpa.parallel_method import ParallelMethod, ShardParallel
15 from …
```

[Simple] Remove deprecated numpy.int/float
