alpa/device_mesh.py
@zhisbug Is this the right fix?
=> [FIX] Fix device_strs

README.md, docs/developer/developer_guide.rst, docs/index.rst
Improve README.md to make it more relevant and catchy to users.
=> [Documentation] move some developer guides to doc

alpa/pipeline_parallel/stage_profiling.py, alpa/shard_parallel/auto_sharding.py
The Alpa side refactor corresponding to https://github.com/alpa-projects/tensorflow-alpa/pull/97.
=> [REFACTOR] Refactor compilation in xla

alpa/pipeline_parallel/stage_construction.py
=> Fix a bug that makes the first DP optimization not working

osdi22_artifact/README.md, osdi22_artifact/deepspeed/benchmark_moe.py, osdi22_artifact/deepspeed/ds_zero_stage_2_moe_config.json, osdi22_artifact/deepspeed/pretrain_gpt2_moe.py, osdi22_artifact/deepspeed/run_deepspeed_benchmark.sh, osdi22_artifact/deepspeed/setup.md, osdi22_artifact/megatron/benchmark_gpt.py, osdi22_artifact/megatron/benchmark_gpt_one_case.py, osdi22_artifact/megatron/run_megatron_benchmark.sh, osdi22_artifact/megatron/setup.md
=> OSDI artifacts baselines: megatron and deepspeed

alpa/monkey_patch.py, tests/test_auto_sharding_basic.py
- Support variadic HloReduce with tuple output
- Fix some bugs in `monkey_patch.py`
depends on https://github.com/alpa-projects/tensorflow-alpa/pull/108
=> Support variadic reduce with tuple output

alpa/mesh_profiling.py, tests/test_install.py
Various tricks to improve the fault tolerance
=> [PORFILING] Fix mesh profling

benchmark/alpa/gather_gpu_stat.py, benchmark/alpa/suite_auto_gpt.py, benchmark/alpa/suite_auto_moe.py, benchmark/alpa/suite_manual_gpt.py
Add 64 GPU performance test benchmark cases
=> [BENCHMARK] Add 64 gpu benchmark cases

alpa/monkey_patch.py
Previous discussion: https://github.com/alpa-projects/alpa/issues/372
=> Add rng_normal support

alpa/api.py, alpa/mesh_executable.py, alpa/pipeline_parallel/apply_grad.py, alpa/pipeline_parallel/base_runtime.py, alpa/pipeline_parallel/decentralized_distributed_runtime.py, alpa/pipeline_parallel/layer_construction.py, alpa/pipeline_parallel/pipeshard_parallel.py, alpa/pipeline_parallel/schedules.py, alpa/pipeline_parallel/stage_construction.py, alpa/util.py, playground/pipeline/test_acc_grad.py, playground/pipeline/test_distributed_compile.py, tests/test_pipeline_stage_construct_util.py
Currently we compile a concat executable and it does not support a following apply grad stage. I'll work on it later, but this version is enough for inference.
=> [FEATURE] Support outvars concatenated in batch dimension

alpa/device_mesh.py, alpa/global_env.py, alpa/mesh_executable.py, alpa/pipeline_parallel/decentralized_distributed_runtime.py, benchmark/alpa/benchmark_2d_one_case_gpt_bert.py, benchmark/alpa/benchmark_2d_one_case_moe.py, benchmark/alpa/benchmark_2d_one_case_wresnet.py, benchmark/alpa/benchmark_3d_one_case.py, benchmark/alpa/benchmark_3d_one_case_gpt_bert.py, benchmark/alpa/benchmark_3d_one_case_moe.py, benchmark/alpa/benchmark_3d_one_case_wresnet.py, benchmark/alpa/suite_manual_gpt.py, examples/imagenet/train.py, tests/test_device_mesh.py, tests/test_install.py
- Improve the speed of sharding input arguments (train_state and batch) for both shard_parallel and pipeshard_parallel.
- Reduce the driver launching overhead
=> [RUNTIME] Improve the speed of sharding input arguments

alpa/pipeline_parallel/pipeshard_executable.py, alpa/testing.py, tests/test_pipeline_inference_only.py
Support returning `last_hidden_state`, `hidden_state` and `attention` in inference.
=> [TEST] Add more inference test

alpa/api.py, alpa/device_mesh.py, alpa/mesh_profiling.py, alpa/parallel_method.py, alpa/pipeline_parallel/compile_executable.py, alpa/pipeline_parallel/computation.py, alpa/pipeline_parallel/pipeshard_executable.py, alpa/serialization.py, alpa/util.py, tests/run_all.py, tests/test_auto_sharding_basic.py, tests/test_dist_save_load.py
Port misc improvements from the opt branch.
- Add `mesh_id` to `MeshHostWorker` and `DistributedPhysicalDeviceMesh`
- Add a fast call to `PipeshardDriverExecutable` without signature matching
- Add a gemv test.
=> Misc improvements for PipeshardExecutable

alpa/mesh_profiling.py, alpa/pipeline_parallel/layer_construction.py, alpa/pipeline_parallel/stage_construction.py, alpa/pipeline_parallel/stage_profiling.py, alpa/util.py, setup.py, tests/test_dynamic_programming.py
=> [FIX] Make numba optional

docs/gallery/tutorials/alpa_vs_pmap.py
=> adding pjit

alpa/device_mesh.py, alpa/util.py
=> [utils] exact check node ip address

tests/torch_frontend/test_dict_input.py, tests/torch_frontend/test_reshape.py, tests/torch_frontend/test_zhen.py
=> Add RNG seed setting to other PT tests

alpa/create_state_parallel.py, alpa/device_mesh.py, alpa/mesh_executable.py, alpa/parallel_plan.py, alpa/pipeline_parallel/pipeshard_executable.py, alpa/pipeline_parallel/runtime_emitter.py, alpa/serialization.py, docs/tutorials/opt_serving.rst, examples/opt_serving/README.md, examples/opt_serving/benchmark/benchmark_text_gen.py, examples/opt_serving/model/opt_model.py, examples/opt_serving/model/wrapper.py, examples/opt_serving/scripts/convert_to_numpy_weights.py, examples/opt_serving/textgen_demo.py, tests/runtime/test_dist_save_load.py
Merge PlacementSpec and LoadInfo. I chose the name "PlacementSpec" because it is not only used for loading a model.
=> Merge PlacementSpec and LoadInfo

alpa/torch/trainer.py, tests/torch_frontend/test_zhen.py
The implementation of current ZHEN has a little mistake. This patch fixes the issue.
=> Correct the implementation of ZHEN

alpa/collective/worker_nccl_util_cupy.py, alpa/collective/worker_nccl_util_xla.py, alpa/device_mesh.py, alpa/util.py, tests/runtime/test_xla_nccl.py
- Separate `collective/mesh_run_nccl_collective.py` into two files `alpa/collective/worker_nccl_util_cupy.py` and `alpa/collective/worker_nccl_util_xla.py`
- Remove all `import cupy` under `alpa/collective`
=> [NFC] Clean up collective

tests/torch_frontend/test_zhen.py
This PR fixes the issues mentioned in https://github.com/alpa-projects/alpa/pull/542#issuecomment-1172019030
Now we should be able to run `tests/torch_frontend/test_zhen.py`.
=> [BUG] Fix bug in ZHEN test

examples/opt_serving/model/wrapper.py, examples/opt_serving/textgen_demo.py
An extension to 14b31536cecdccfea8e043d538f4b034be1063a8 to enable the return on multiple outputs.
=> [FEATURE] Allow num_return_sequences > 1 (#491)

alpa/collective/collective.py, alpa/collective/collective_group/gloo_collective_group.py, alpa/device_mesh.py, alpa/util.py
i got the lint 
```python
Alpa Pylint:
************* Module alpa.device_mesh
alpa/device_mesh.py:1108:8: W0702: No exception type(s) specified (bare-except)
alpa/device_mesh.py:1957:8: W0702: No exception type(s) specified (bare-except)
************* Module alpa.collective.collective
alpa/collective/collective.py:741:12: W0702: No exception type(s) specified (bare-except)
alpa/collective/collective.py:742:25: W0212: Access to a protected member _private of a client class (protected-access)
alpa/collective/collective.py:797:4: W0702: No exception type(s) specified (bare-except)
alpa/collective/collective.py:798:17: W0212: Access to a protected member _private of a client class (protected-access)
************* Module alpa.collective.collective_group.gloo_collective_group …
```
=> try to fix the issue mentioned in issue #610

alpa/api.py, alpa/data_loader.py, alpa/device_mesh.py, alpa/parallel_method.py, alpa/test_install.py, alpa/util.py, examples/imagenet/train.py, tests/runtime/test_device_mesh.py
- Use 1d logical mesh by default
- Fix a bug in data loader
- Fetch train metrics in a batch
=> [Example] Improve imagenet example

docker/serving_alpa.Dockerfile
env:cuda113/cudnn820
eg : docker pull ggkrepo/alpa:0.0.1
=> [Docker]Provide a alpa runtime docker image

alpa/__init__.py, alpa/api.py, alpa/device_mesh.py, alpa/follow_parallel.py, alpa/model/model_util.py, alpa/monkey_patch.py, alpa/parallel_method.py, alpa/pipeline_parallel/pipeshard_executable.py, alpa/shard_parallel/compile_executable.py, alpa/test_install.py, alpa/testing.py, alpa/util.py, docs/gallery/tutorials/pipeshard_parallelism.py, docs/gallery/tutorials/quickstart.py, examples/imagenet/train.py, examples/language_model/README.md, examples/language_model/run_clm_flax.py, examples/mnist/train.py, examples/mnist/train_ray.py, examples/opt_finetune/README.md, examples/opt_finetune/run_clm_flax.py, tests/pipeline_parallel/test_inference_only.py
- Add an OPT fine-tuning example
=> [Example] Fine-tune pre-trained OPT models from huggingface

README.md, alpa/shard_parallel/auto_sharding.py, docs/install.rst, setup.py
- Update pulp version
- Use the built-in cbc binary in pulp
=> Update pulp version

alpa/device_mesh.py, alpa/pipeline_parallel/stage_construction.py, alpa/pipeline_parallel/stage_profiling.py, alpa/util.py, tests/pipeline_parallel/test_stage_construction.py
- Fix placement group for `HloCostModelProfileWorkerPool` after (#634 ). This class is not tested in the unit test.
- various small improvements
=> [RUNTIME] Fix ray placement group

examples/opt_serving/README.rst, examples/opt_serving/benchmark/benchmark_text_gen.py, examples/opt_serving/generator.py, examples/opt_serving/interactive_hosted.py, examples/opt_serving/model/opt_model.py, examples/opt_serving/model/wrapper.py, examples/opt_serving/textgen_demo.py
- Now for OPT 125M-66B, we don't need to do manual weight conversion. We can automatically download the weights from hugging face and convert them to alpa format if there are no existing cached weights.
- Update weight format from `qvk_combined` to `qkv_combined`
=> [OPT] Download weights automatically from huggingface

examples/opt_serving/client.py, examples/opt_serving/interactive_hosted.py, examples/opt_serving/service/constants.py, examples/opt_serving/test_completions.py, examples/opt_serving/test_logprobs.py
Redirect logprob end point to workaround some security settings
=> [OPT Serving] Redirect logprob end point 

examples/setup.py
Fix setup.py after we remove dataset folder #669
=> [Fix] Fix the opt_serving setup.py

examples/opt_serving/README.rst, examples/opt_serving/client.py, examples/opt_serving/interactive_hosted.py, examples/opt_serving/service/index.html, examples/opt_serving/service/recaptcha.py, examples/opt_serving/service/utils.py, examples/opt_serving/test_completions.py, examples/opt_serving/test_logprobs.py
Add recaptcha and api keys to prevent unauthenticated users.
=> Add recaptcha and api keys

docs/install.rst, examples/opt_serving/README.rst, examples/opt_serving/benchmark/benchmark_text_gen.py, examples/opt_serving/generator.py, examples/opt_serving/model/opt_model.py, examples/opt_serving/model/wrapper.py, examples/opt_serving/test_completions.py, examples/opt_serving/test_logprobs.py
- Remove auto-regressive model in opt
- Minor updates of docs
=> [NFC] Minor update of docs and examples

alpa/pipeline_parallel/computation.py, examples/llm_serving/generator.py, examples/llm_serving/model/bloom_model.py, examples/llm_serving/model/opt_model.py, examples/llm_serving/model/wrapper.py, examples/llm_serving/scripts/step_3_convert_to_numpy_weights.py, examples/llm_serving/textgen.py, tests/pipeline_parallel/test_mlp.py
- Port the bloom implementation from https://github.com/alpa-projects/alpa/pull/691 and merge it with the existing opt code to share code.
- Now the scripts automatically download the bloom weights from hugggingface and convert them into alpa format
- Rename some members in `OptConfig` and `BloomConfig` to make them identical so that they can share the code.
- Fix various bugs in pipeshard parallel (constant handling) and auto-sharding
This PR modifies the name of the path of the weight folder to avoid the conflict of multiple models. Please rename your existing weight folders.  For example, `opt_weights/175B_np` should be renamed to `opt_weights/opt-175b-np`, `opt_weights/2.7B_np` should be renamed to `opt_weights/opt-2.7b-np`
1. The results with batch size > 1 are incorrect. If batch …
=> [Example] Add bigscience/bloom to llm_serving

alpa/model/bert_model.py, examples/llm_serving/benchmark/benchmark_step_func.py, examples/llm_serving/model/bloom_model.py
- Update tensorflow-alpa submodule for this iota fix (https://github.com/alpa-projects/tensorflow-alpa/pull/133)
- Fix related test cases
=> Update tensorflow-alpa submodule

alpa/__init__.py, alpa/api.py, alpa/collective/collective_group/nccl_util.py, alpa/global_env.py, alpa/mesh_executable.py, alpa/pipeline_parallel/computation.py, alpa/pipeline_parallel/layer_stats.py, alpa/pipeline_parallel/runtime_emitter.py, alpa/shard_parallel/auto_sharding.py, alpa/util.py, alpa/version.py, docs/install.rst, tests/pipeline_parallel/test_bert.py, tests/pipeline_parallel/test_mlp.py
- Do not init GPU backend on the driver
- Lazily check jaxlib version
- Enable parallelized GPU compilation
=> Do not init GPU backend on the driver

alpa/api.py, alpa/device_mesh.py, alpa/mesh_executable.py, alpa/serve/controller.py, alpa/serve/http_util.py, alpa/serve/run.py, alpa/util.py, docker/unittest.Dockerfile, examples/llm_serving/model/opt_model_1d.py, tests/runtime/test_device_mesh.py, tests/serve/test_controller.py
Add a multi-model serving controller
=> [Serve] Add controller

examples/llm_serving/model/wrapper.py
Add unk_token_id of bloom, set special token_ids to their values in bloom for inference with bloom.
=> Add special tokens used by BloomModel to wrapper.py

docs/install.rst
Issue: https://github.com/alpa-projects/alpa/issues/729
Description: Added troubleshooting information about IO virtualization to the install docs.
=> [DOCS] Add IOMMU info to install.rst

README.md, examples/llm_serving/README.rst, examples/llm_serving/generator.py, examples/llm_serving/launch_model_worker.py, examples/llm_serving/model/wrapper.py, examples/llm_serving/test_textgen.sh, examples/llm_serving/textgen.py
Address https://github.com/alpa-projects/alpa/issues/734
=> configurable tokenizer name

examples/llm_serving/launch_model_worker.py
Address https://github.com/alpa-projects/alpa/issues/755
=> Handle x forwarded for header

alpa/__init__.py, alpa/create_state_parallel.py, alpa/follow_parallel.py, alpa/mesh_executable.py, alpa/pipeline_parallel/compile_executable.py, alpa/pipeline_parallel/computation.py, alpa/pipeline_parallel/cross_mesh_resharding.py, alpa/pipeline_parallel/layer_stats.py, alpa/pipeline_parallel/pipeshard_executable.py, alpa/pipeline_parallel/runtime_emitter.py, alpa/pipeline_parallel/stage_profiling.py, alpa/shard_parallel/auto_sharding.py, alpa/shard_parallel/compile_executable.py, alpa/util.py, alpa/wrapped_hlo.py
See https://github.com/alpa-projects/alpa/issues/765
=> [Refactor] Use WrappedHlo to record HloStatus with HloModule

tests/shard_parallel/test_basic.py
https://github.com/alpa-projects/tensorflow-alpa/pull/137
=> [Fix] Fix the auto-sharding bug of gather

alpa/device_mesh.py, alpa/global_env.py, alpa/mesh_executable.py, alpa/util.py
1. add xla server port config when the docker port are limited to special range  like 8000~8999, should fix  https://github.com/alpa-projects/alpa/issues/826 
2. conner case when next_batches_uuids ==(None,) should fix https://github.com/alpa-projects/alpa/issues/797
3.
=> Add xla server port config and pass next batches uuids ==(none,)

docs/gallery/tutorials/pipeshard_parallelism.py
=> [Docs] Fix typo in pipeshard_parallelism.py

docs/index.rst, docs/slurm_script_examples/test_cuda.sh, docs/slurm_script_examples/test_prerequisites.sh, docs/slurm_script_examples/test_ray_multinode.sh, docs/slurm_script_examples/textgen_alpa_test.sh, docs/slurm_script_examples/textgen_pt_test.sh, docs/tutorials/alpa_on_slurm.rst
As mentioned by Issue #751 that the given link in the current docs for using Alpa on Ray on Slurm is broken. Hence, after using Slurm for one month, I wrote this guide, hoping to add to the tutorial section of docs and help people with access of Slurm to deploy Alpa.
=> [DOC] Add guide for deploying on Slurm

alpa/collective/collective_group/nccl_collective_group.py, alpa/collective/collective_group/xla_nccl_collective_group.py, alpa/device_mesh.py, alpa/pipeline_parallel/apply_grad.py, alpa/pipeline_parallel/compile_executable.py, alpa/pipeline_parallel/pipeshard_executable.py, alpa/util.py, tests/pipeline_parallel/test_global_norm.py, tests/runtime/test_cross_mesh_communicator.py
Corresponding to https://github.com/alpa-projects/tensorflow-alpa/pull/140
=> [FIX] fix setting cross mesh communicator for each group

alpa/torch/__init__.py
Hi, 
I am looking into using the PT frontend for Alpa. The current code works for PT1.12 but breaks for PT1.13 and PT2. To get the tests in `torch_frontend/*` to pass for PT2, I had to update some of the functorch imports under `alpa/torch/__init__.py`. The tests pass but let me know if there is some additional testing that needs to be done to update the PT frontend.
=> updated functorch imports for PyTorch2 frontend

benchmark/alpa/resharding/README.md
=> [DOC] fix typo in resharding/README.md

alpa/device_mesh.py
This PR fix AttributeError raised in DistributedArray.block_until_ready 
Closes #904
=> Fix DistributedArray.block_until_ready AttributeError

alpa/pipeline_parallel/runtime_emitter.py
some minor fixes for a previous incorrect merge in https://github.com/alpa-projects/alpa/pull/876
=> [FIX] clean code in runtime emitter

alpa/api.py, alpa/device_mesh.py
=> Allow users to specify a different cluster address when initializing Ray

alpa/api.py, alpa/collective/worker_nccl_util_cupy.py, alpa/collective/worker_nccl_util_xla.py, alpa/device_mesh.py, alpa/global_env.py, alpa/mesh_executable.py, alpa/mesh_profiling.py, alpa/model/model_util.py, alpa/monkey_patch.py, alpa/pipeline_parallel/compile_executable.py, alpa/pipeline_parallel/computation.py, alpa/pipeline_parallel/layer_construction.py, alpa/pipeline_parallel/runtime_emitter.py, alpa/pipeline_parallel/stage_profiling.py, alpa/shard_parallel/auto_sharding.py, alpa/shard_parallel/compile_executable.py, alpa/shard_parallel/manual_sharding.py, alpa/util.py, alpa/version.py, alpa/wrapped_hlo.py, build_jaxlib/.bazelrc, build_jaxlib/WORKSPACE, build_jaxlib/build/build.py, build_jaxlib/build/build_wheel.py, tests/pipeline_parallel/test_bert.py, tests/pipeline_parallel/test_global_norm.py, tests/shard_parallel/test_basic.py, tests/shard_parallel/test_bert.py, tests/shard_parallel/test_mlp.py
=> Rebase ALPA onto JAX v0.4.6
